[[getcustomasset.args]]
type = "string"
[[getsynasset.args]]
type = "string"
[[request.args]]
type = "table"
[[makefolder.args]]
type = "string"
[[delfolder.args]]
type = "string"
[[writefile.args]]
type = "string"
[[writefile.args]]
type = "string"
[[readfile.args]]
type = "string"
[[isfile.args]]
type = "string"
[[isfolder.args]]
type = "string"
[getgenv]
args = []
[syn]
property = true
writable = "new-fields"
