name: CI

on:
	push:
		branches: [master]
	pull_request:
		branches: [master]

jobs:
	prebuild:
		name: Pre-build checks
		runs-on: ubuntu-latest
		steps:
			- name: Checkout repo
				uses: actions/checkout@v2

			- name: Install Node.js v14
				uses: actions/setup-node@v2
				with:
					node-version: "14"

			- name: Install dependencies
				run: npm install

			- name: Run yarn lint
				run: yarn lint
				if: success()

	build:
		name: Build
		needs: prebuild
		runs-on: ubuntu-latest
		steps:
			- name: Checkout repo
				uses: actions/checkout@v2

			- name: Install Node.js v14
				uses: actions/setup-node@v2
				with:
					node-version: "14"

			- name: Install dependencies
				run: yarn

			- name: Install foreman
				uses: Roblox/setup-foreman@v1
				with:
					token: ${{ secrets.GITHUB_TOKEN }}

			- name: Run roblox-ts compiler
				run: yarn compile

			- name: Build model with Rojo
				run: yarn rojo

			- name: Build rbxmSuite
				run: yarn build:min

			- name: Upload release artifact
				uses: actions/upload-artifact@v2
				with:
					name: rbxm-suite
					path: ./rbxmSuite.lua
