name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Minify rbxm-suite
        run: npm run min

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: rbxm-suite.lua
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
